spring.datasource.url=jdbc:postgresql://dpg-d993m18k1i2s73djrukg-a.oregon-postgres.render.com:5432/crm_project_norl

spring.datasource.username=crm_project_norl_user

spring.datasource.password=55NV9RykHRu4kxU8PVoujSidilzSQlaN

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect